// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DependencyGraph
{
    internal sealed partial class Vsix
    {
        public const string Id          = "DependencyGraph.b16f35c3-ecb1-4300-82b8-c04a14f874cb";
        public const string Name        = "DependencyGraph";
        public const string Description = @"Display visual studio project dependency graph.";
        public const string Language    = "en-US";
        public const string Version     = "2023.3.0.3";
        public const string Author      = "Lokesh Govindu";
        public const string Tags        = "DependencyGraph";
    }
}
